name: CD - Build, Push and Deploy

on:
  push:
    branches:
      - main
      - 'devops/**'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  docker:
    name: Build and Push Docker Image
    runs-on: [self-hosted, Linux, X64]

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          docker build \
            -t ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER:latest \
            .

      - name: Push Docker image
        run: |
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          docker push \
            ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER:${{ github.sha }}

          docker push \
            ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER:latest


  deploy:
    name: Deploy on Self-Hosted Server
    needs: docker
    runs-on: [self-hosted, Linux, X64]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify server environment
        run: |
          echo "===== SERVER ====="
          hostname

          echo "===== USER ====="
          whoami

          echo "===== DIRECTORY ====="
          pwd

          echo "===== DOCKER ====="
          docker --version

          echo "===== DOCKER COMPOSE ====="
          docker compose version

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Deploy application
        run: |
          cd ~/solarFix

          export IMAGE_TAG="${{ github.sha }}"

          docker compose pull

          docker compose up -d

          docker image prune -f

      - name: Verify deployment
        run: |
          cd ~/solarFix

          docker compose ps
